version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: wind-chaser-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: wind-chaser
    volumes:
      - mongodb_data:/data/db
    networks:
      - wind-chaser-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: wind-chaser-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/wind-chaser
      - JWT_SECRET=dev-jwt-secret-key
      - FRONTEND_URL=http://localhost:3000
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongodb
    networks:
      - wind-chaser-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: wind-chaser-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - wind-chaser-network

volumes:
  mongodb_data:

networks:
  wind-chaser-network:
    driver: bridge
